library(GEOquery)
library(RCurl)
library(GEOmetadb)
library(reshape)
library(ggplot2)
library(gplots)
library(RColorBrewer)



#################
## Pulling GEO Datasets
################


### Pull all 450K studies under GPL13534 
getSQLiteFile()
con <- dbConnect(SQLite(), "GEOmetadb.sqlite")
dbListFields(con, "gsm")
x<-dbGetQuery(con, "select title,description,series_id,gsm,source_name_ch1,characteristics_ch1 from gsm where gpl='GPL13534'")
meta<-x
print(paste("Samples: ",nrow(meta), "   Studies: ", length(unique(meta$series_id)), sep=""))


### search for terms that tissue samples would likely be under
blood_meta<-meta[unique(c(grep("blood|Blood",meta$source_name_ch1),
                          grep("blood|Blood",meta$title), 
                          grep("blood|Blood",meta$characteristics_ch1))) ,]
print(paste("Blood Samples: ",nrow(blood_meta), "   Blood Studies: ", length(unique(blood_meta$series_id)), sep=""))


#Exclude samples that may not actually be the tissue of interest, non-human samples and cancer
#These exclusion terms can be generated by looking through the terms present for terms you don't want
unique(blood_meta$source_name_ch1)
unique(blood_meta$characteristics_ch1)
unique(blood_meta$title)

blood_meta<-blood_meta[-grep("Brain|AML|leukemia|B-cell|gyrus|cortex|PBMC|CD19+|cerebellum|peripheral|cancer|marrow|troglodytes|vaginal|B cells|Peripheral|Cord|cord", blood_meta$source_name_ch1),]
blood_meta<-blood_meta[-grep("Chimpanzee|paniscus|B cells|troglodytes|gorilla|Pongo|cerebellum|cortex|gyrus", blood_meta$title),]

print(paste("Blood Samples: ",nrow(blood_meta), "   Blood Studies: ", length(unique(blood_meta$series_id)), sep=""))


## Name which series to download off GEO
series<-unique(blood_meta$series_id)
table(as.character(blood_meta$series_id))

series<-c(series[c(1,3,5,6,8:12,15,18:32,36,38,40:53)])
blood_meta<-blood_meta[which(blood_meta$series_id%in%series),]

blood_meta<-blood_meta[,c("series_id","gsm")]
blood_meta$tissue<-"Blood"

save(blood_meta, file="Meta_blood.RData")

print(paste("Blood Samples: ",nrow(blood_meta), "   Blood Studies: ", length(unique(blood_meta$series_id)), sep=""))


# Pull the actual beta values from GEO
#in batches as pulling them all at once filled the tmp directory
GEO1<-lapply(series[1:10], function(x) as.data.frame(exprs(getGEO(x)[[1]])))
GEO2<-lapply(series[11:20], function(x) as.data.frame(exprs(getGEO(x)[[1]])))
GEO3<-lapply(series[21:30], function(x) as.data.frame(exprs(getGEO(x)[[1]])))

save(GEO1, file="GEO3_blood.RData") # x series; x probes 
save(GEO2, file="GEO3_blood.RData") # x series; x probes 
save(GEO3, file="GEO3_blood.RData") # x series; x probes 

#combine into one dataframe
load("GEO1_blood.RData")
load("GEO2_blood.RData")
load("GEO3_blood.RData")

GEO<-GEO1
GEO[11:20]<-GEO2
names(GEO)[11:20]<-names(GEO2)
GEO[21:30]<-GEO3
names(GEO)[21:30]<-names(GEO3)

sum(sapply(1:length(GEO), function(x) ncol(GEO[[x]]))) # Samples

save(GEO, file="GEO_blood.RData") # x series; x probes 






#################
## Quality Control 
################

## Identify the probes present in all studies of a tissue
load("GEO_blood.RData")
load("Meta_blood.RData")
sapply(1:length(GEO), function(x) nrow(GEO[[x]]))
sapply(1:length(GEO), function(x) ncol(GEO[[x]]))

# remove the data sets with no or very few probes (ie pre-filtered to less than ~400,000)
GEO<-GEO[c(1:5,7,8,10,12,14,17,18,20,22:27,29,30)]

GEO_more_probes<-lapply(1:length(GEO), function(x) GEO[[x]][which(rownames(GEO[[x]])%in%rownames(GEO[[16]])),])
GEO_more_probes<-lapply(1:length(GEO_more_probes), function(x) GEO_more_probes[[x]][which(rownames(GEO_more_probes[[x]])%in%rownames(GEO_more_probes[[13]])),])
GEO_more_probes<-lapply(1:length(GEO_more_probes), function(x) GEO_more_probes[[x]][which(rownames(GEO_more_probes[[x]])%in%rownames(GEO_more_probes[[11]])),])
GEO_more_probes<-lapply(1:length(GEO_more_probes), function(x) GEO_more_probes[[x]][which(rownames(GEO_more_probes[[x]])%in%rownames(GEO_more_probes[[10]])),])

sapply(1:length(GEO_more_probes), function(x) nrow(GEO_more_probes[[x]])) # 469987 probes for blood

#CONVERT m TO BETA if need be (if the range of values if more than 0-1)
range<-sapply(1:length(GEO_more_probes), function(x) max(GEO_more_probes[[x]][1,], na.rm=T)-min(GEO_more_probes[[x]][1,], na.rm=T))

GEO_betas<-do.call(cbind, GEO_more_probes)# 469987 probes in all datasets
GEO_betas_blood<-GEO_betas[,which(colnames(GEO_betas)%in%blood_meta$gsm)]# 469987    883
save(GEO_betas_blood, file="Blood_Betas.RData")






## Density plots
load(file="Blood_Betas.RData")
load("Meta_blood.RData")

blood_meta<-blood_meta[which(blood_meta$gsm%in%colnames(GEO_betas_blood)),]
blood_meta<-blood_meta[match(colnames(GEO_betas_blood),blood_meta$gsm),]
blood_meta<-blood_meta[,c(3,4)]

Beta_sample<-GEO_betas_blood[sample(1:485577, 10000),]

Beta_sample$CpG<-rownames(Beta_sample)
Beta_sample_melted<- melt(Beta_sample)
#remove NAs before plotting (otherwise get many non-inifnite warnings)
Beta_Plot<-Beta_sample_melted[which(!(is.na(Beta_sample_melted$value))),]
#add meta
Beta_Plot<-merge(Beta_Plot,blood_meta, by.x="variable", by.y="gsm")

## Color by series
Beta_Plot_series<-as.data.frame(with(Beta_Plot, tapply(value, list(CpG, series_id), mean, na.rm=T)))
Beta_Plot_series$CpG<-rownames(Beta_Plot_series)
Beta_Plot_series_melted<- melt(Beta_Plot_series)
#remove NAs before plotting (otherwise get many non-inifnite warnings)
Beta_Plot_series_melted_blood<-Beta_Plot_series_melted[which(!(is.na(Beta_Plot_series_melted$value))),]
#add meta

blood_meta$series_id<-as.factor(blood_meta$series_id)
selcol <- colorRampPalette(brewer.pal(9,"Set1"))
clustcol.height_blood = selcol(length(unique(blood_meta$series_id)))

density_blood<-ggplot(Beta_Plot_series_melted_blood, aes(value, group=variable, color=variable))+
  geom_density()+theme_bw()+ylim(0,2.75)+scale_color_manual(values=clustcol.height_blood)+xlab("Beta Value")
density_blood




## Remove probes with high NA count
dim(GEO_betas_blood)
na_count_sample <-sapply(GEO_betas_blood, function(y) sum(length(which(is.na(y)))))
na_count_sample_good<-which(na_count_sample<(nrow(GEO_betas_blood)*0.025))
GEO_betas_blood_good<-GEO_betas_blood[,na_count_sample_good]
dim(GEO_betas_blood_good)
na_count_probe <-sapply(1:nrow(GEO_betas_blood_good), function(y) length(which(is.na(GEO_betas_blood_good[y,]))))
na_count_probe_good<-which(na_count_probe<(ncol(GEO_betas_blood_good)*0.05))
GEO_betas_blood_good<-GEO_betas_blood_good[na_count_probe_good,]
dim(GEO_betas_blood_good)





## Sample-Sample Correlations
## errors if the samples with many NAs are left in
na_count_sample <-sapply(GEO_betas_blood, function(y) sum(length(which(is.na(y)))))
na_count_sample_good<-which(na_count_sample<(nrow(GEO_betas_blood)*0.025))
GEO_betas_blood_good<-GEO_betas_blood[,na_count_sample_good]

blood_meta<-blood_meta[which(blood_meta$gsm%in%colnames(GEO_betas_blood_good)),]
blood_meta<-blood_meta[match(colnames(GEO_betas_blood_good),blood_meta$gsm),]

## order samples 
blood_meta<-blood_meta[which(blood_meta$gsm%in%colnames(GEO_betas_blood_good)),]
blood_meta<-blood_meta[match(colnames(GEO_betas_blood_good),blood_meta$gsm),]
GEO_betas_blood_good<-GEO_betas_blood_good[,order(colnames(GEO_betas_blood_good))]
blood_meta<-blood_meta[order(blood_meta$gsm),]

## Correlation
corr_blood<-cor(GEO_betas_blood_good, use="complete.obs", method="spearman")

blood_meta$series_id<-as.factor(blood_meta$series_id)

# Colors setting 
hmcols <-  colorRampPalette(brewer.pal(9,"Blues"))
selcol <- colorRampPalette(brewer.pal(9,"Set1"))
clustcol.height_blood = selcol(length(unique(blood_meta$series_id)))
cols_blood<-clustcol.height_blood[as.numeric(blood_meta$series_id)]

heatmap.2(as.matrix(corr_blood),Colv=FALSE,Rowv=FALSE,
          density.info="none",scale="none",ColSideColors=cols_blood,RowSideColors=cols_blood,
          margin=c(10,10),col=hmcols,symkey=F,trace="none",dendrogram="none",
          labRow=NA,
          labCol=NA, breaks=seq(0.8, 1, 0.01))

legend("topright",      
       legend = levels(blood_meta$series_id),
       col = clustcol.height_blood, 
       lty= 1,             
       lwd = 4,           
       cex=1
)


## Average sample correlation
average_sample_correlation_blood<-colMeans(corr_blood)

blood_meta$ave_samp_cor<-average_sample_correlation_blood
ggplot(blood_meta, aes(gsm, ave_samp_cor, color=series_id))+geom_point(shape=19, size=1)+theme_bw()+scale_color_manual(values=clustcol.height_blood, name="Series ID")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        axis.ticks = element_blank(), axis.text.x = element_blank())+xlab("Sample")+ylab("Mean Sample Correlation")+
  ylim(0.8,1)+ guides(colour = guide_legend(override.aes = list(size = 7, shape=15)))


###################################Filter series with low sample correlation across all samples

# GSE50837, GSE53840, GSE53841, GSE58651

low_cor_series<-c("GSE50837", "GSE53840", "GSE53841", "GSE58651")
blood_meta_QC_passed<-blood_meta[which(!(blood_meta$series_id%in%low_cor_series)),]

GEO_betas_blood_QC_passed<-GEO_betas_blood_good[,which(colnames(GEO_betas_blood_good)%in%blood_meta_QC_passed$gsm)]

GEO_betas_blood_good<-GEO_betas_blood_QC_passed
save(GEO_betas_blood_good, file="GEO_betas_blood_good.RData")

#################
## Call Non-variable CpGs
################
###### Calculate reference range varibility (without low correlation studies, and high NA probes)
load("GEO_betas_blood_good.RData")

Variation<-function(x) {quantile(x, c(0.9), na.rm=T)[[1]]-quantile(x, c(0.1), na.rm=T)[[1]]}

ref_range_blood<-lapply(1:nrow(GEO_betas_blood_good), function(x) Variation(GEO_betas_blood_good[x,]))
save(ref_range_blood, file="Reference_ranges_Blood.RData")

### Count the non-variable CpGs
load("GEO_betas_blood_good.RData")
load("Reference_ranges_Blood.RData")
ref_range_blood<-unlist(ref_range_blood)
length(which(ref_range_blood<0.05))

nonvariable_blood<-GEO_betas_blood_good[which(ref_range_blood<0.05),]

Blood_nonvariable_cpgs<-data.frame(CpG=rownames(nonvariable_blood), RefRange=ref_range_blood[which(ref_range_blood<0.05)])
write.csv(Blood_nonvariable_cpgs, file="Nonvariable_Blood_CpGs.csv")
